language: python
matrix:
  include:
    - os: linux
      env:
        - PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages/
        - PYTHON_EXEC=python
        - PIP=pip
      addons:
        apt:
          packages:
            - python-numpy
    - os: linux
      env:
        - PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/
        - PYTHON_EXEC=python3
        - PIP=pip3
      addons:
        apt:
          packages:
            - python3
            - python3-numpy
            - python3-pip
install:
  - sudo $PIP install 'cython==0.27.3'
  - git clone git://github.com/OctoMap/octomap.git octomap_cpp
  - cd octomap_cpp
  - git checkout v1.8.0
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd ../..
before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
script:
  - sudo $PYTHON_EXEC setup.py install
  - cd test;$PYTHON_EXEC octomap_test.py
